specVersion: 0.0.4
schema:
  file: ./schema.graphql
dataSources:
  {{#HubPool}}
  - kind: ethereum
    name: HubPool
    network: mainnet
    source:
      address: "0xc186fa914353c44b2e33ebe05f21846f1048beda"
      abi: HubPool
      startBlock: 14819537
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - LiquidityAdded
        - LiquidityRemoved
      abis:
        - name: HubPool
          file: ./abis/HubPool.json
        ################################################ 
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: LiquidityAdded(indexed address,uint256,uint256,indexed address)
          handler: handleLiquidityAdded
        - event: LiquidityRemoved(indexed address,uint256,uint256,indexed address)
          handler: handleLiquidityRemoved
      file: ./src/handlers/liquidity.ts
  {{/HubPool}}
  {{#SpokePool}}
  - kind: ethereum
    name: SpokePool
    network: {{ network }}
    source:
      address: "{{ address }}"
      abi: SpokePool
      startBlock: {{ startBlock }}
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - BridgeProtocolA
        - FinancialsDailySnapshot
        - UsageMetricsDailySnapshot
        - UsageMetricsHourlySnapshot
        - Token
        - CrosschainToken
        - Pool
        - PoolDailySnapshot
        - PoolHourlySnapshot
        - PoolRoute
        - PoolRouteSnapshot   
      abis:
        - name: SpokePool
          file: ./abis/SpokePool.json
        - name: AcceleratingDistributor
          file: ./abis/AcceleratingDistributor.json
        ################################################ 
        # ERC20
        - name: _ERC20
          file: ./abis/Prices/ERC20.json
        # Curve Contracts
        - name: CurvePool
          file: ./abis/Prices/Curve/Pool.json
        - name: CurveRegistry
          file: ./abis/Prices/Curve/Registry.json
        - name: CalculationsCurve
          file: ./abis/Prices/Calculations/Curve.json
        # YearnLens Contracts
        - name: YearnLensContract
          file: ./abis/Prices/YearnLens.json
        # Aave Oracle Contract
        - name: AaveOracleContract
          file: ./abis/Prices/AaveOracle.json
        # SushiSwap Contracts
        - name: CalculationsSushiSwap
          file: ./abis/Prices/Calculations/SushiSwap.json
        # ChainLink Contracts
        - name: ChainLinkContract
          file: ./abis/Prices/ChainLink.json
        # Uniswap Contracts
        - name: UniswapRouter
          file: ./abis/Prices/Uniswap/Router.json
        - name: UniswapFactory
          file: ./abis/Prices/Uniswap/Factory.json
        - name: UniswapPair
          file: ./abis/Prices/Uniswap/Pair.json
      eventHandlers:
        - event: FilledRelay(uint256,uint256,uint256,uint256,uint256,uint256,uint64,uint64,uint64,uint32,address,indexed address,indexed address,address,bool)
          handler: handleFilledRelay
      file: ./src/handlers/transfers.ts
  {{/SpokePool}}